Поиск по названию фильмов и по режиссеру
Kriglzz/java-filmorate pull request #18
Opened 2024-03-11 16:31 UTC by eliizaveta

Добавила поиск и поправила пару мелочей, на которые кричала идея

2024-03-11 16:37 UTC, SnezhanaB approved these changes

2024-03-12 07:54 UTC, Kriglzz requested changes

2024-03-12 07:54 UTC, Kriglzz commented on src/main/java/ru/yandex/practicum/filmorate/service/InMemoryFilmService.java
> +    public List<Film> getFilmsByQuery(String query, String by) {
Пожалуйста через интерфейс FilmService

2024-03-12 13:56 UTC, Kriglzz approved these changes

2024-03-12 13:56 UTC, merged