Add database
Kriglzz/java-filmorate pull request #8
Opened 2024-02-24 15:07 UTC by Kriglzz

2024-02-24 22:41 UTC, andrew-larkin requested changes
Привет! Очень хорошо, большая часть реализована корректно - местами поправить код и тесты (2 штуки падают из-за некорректного внедрения завимости). Если не будет получаться - пиши в личку в Пачке, разберемся.

2024-02-24 22:41 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    public List<Map<String, Object>> getGenres() {
возвращать лучше просто список, без мапы

2024-02-24 22:41 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    public Map<String, Object> getGenreById(@PathVariable int id) {
здесь тоже

2024-02-24 22:41 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +    public List<Map<String, Object>> getMpa() {
такая же ситуация

2024-02-24 22:41 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmStorage.java
> +    public Film addFilm(Film film);
в интерфейсе не нужны модификаторы доступа. помимо этого, если ты возвращаешь единственный объект из БД, его следует обернуть в Optional. а в сервисе потом уже достать объект с помощью .orElseThrow() , чтобы обезопасить нас от NPE - актуально для всех методов в интерфейсах Storage

2024-02-24 22:41 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +import java.util.Map;
тут тоже никаких модификаторов доступа не требуется у методов

2024-02-24 22:41 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/service/InMemoryFilmService.java
> +
закомментированный код удаляем

2024-02-24 22:41 UTC, andrew-larkin commented on src/main/resources/application.properties
> +# ? jdbc-url ???????, ??? ?????? ????? ????????? ? ????
удаляем

2024-02-24 22:41 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/InMemoryUserServiceTest.java
> +    private final JdbcTemplate jdbcTemplate;
в контекст не подгружается. попробуй использовать аннотацию над классом @JdbcTest или @SpringBootTest

2024-02-24 22:41 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/InMemoryFilmServiceTest.java
> +    private final JdbcTemplate jdbcTemplate;
тут тоже внедрение не происходит корректным образом, можешь попробовать использовать @SpringBootTest. плюс ко всему ты можешь подгрузить схему БД в тестовую базу, чтобы использовать объекты прямо оттуда

2024-02-25 17:24 UTC, Kriglzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    public List<Map<String, Object>> getGenres() {
Не уверен, как это можно сделать через лист, учитывая тз. Либо я что-то упускаю

2024-02-27 16:06 UTC, merged